package com.reports.hibernate.entity.relations.manyToMany;

import com.reports.hibernate.base.BaseTest;
import com.reports.hibernate.model.entity.relations.manyToMany.unidirectional.UnidirectionalManyToManyChild;
import com.reports.hibernate.model.entity.relations.manyToMany.unidirectional.UnidirectionalManyToManyParent;
import com.reports.hibernate.sql.query.assertion.AssertQueryCount;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.domain.EntityScan;

import java.util.HashSet;
import java.util.Set;

@EntityScan("com.reports.hibernate.model.entity.relations.manyToMany.unidirectional") // scan only required entities
@DisplayName("Unidirectional ManyToMany relationship")
class UnidirectionalManyToManyTests extends BaseTest {

    @Test
    @DisplayName("One sided saving of parents")
    void oneSidedSaveOfParent() {
        int parentsAmount = 3;
        int childrenAmount = 3;
        Set<UnidirectionalManyToManyChild> children = generateChildren(parentsAmount);
        Set<UnidirectionalManyToManyParent> parents = generateParents(childrenAmount);

        for (UnidirectionalManyToManyParent parent : parents) {
            parent.setChildren(children);
            session.persist(parent);
            session.flush();
        }

        assertAll(
                () -> AssertQueryCount.assertInsertCount(
                        childrenAmount + parentsAmount + childrenAmount * childrenAmount)
        );
    }

    private Set<UnidirectionalManyToManyChild> generateChildren(int amount) {
        Set<UnidirectionalManyToManyChild> result = new HashSet<>();
        for (int i = 0; i < amount; i++) {
            UnidirectionalManyToManyChild child = new UnidirectionalManyToManyChild();
            // id autogenerated
            child.setChildName("Child № " + i);
            result.add(child);
        }
        return result;
    }

    private Set<UnidirectionalManyToManyParent> generateParents(int amount) {
        Set<UnidirectionalManyToManyParent> result = new HashSet<>();
        for (int i = 0; i < amount; i++) {
            UnidirectionalManyToManyParent child = new UnidirectionalManyToManyParent();
            // id autogenerated
            child.setParentName("Parent № " + i);
            result.add(child);
        }
        return result;
    }

}
